export enum EmailTemplates {
  RESET_PASSWORD_NCZ = "RESET_PASSWORD_NCZ",
  VERIFY_EMAIL_NCZ = "VERIFY_EMAIL_NCZ",
  RESET_PASSWORD_SG = "RESET_PASSWORD_SG",
  VERIFY_EMAIL_SG = "VERIFY_EMAIL_SG",
  BLUE_AWARD_REPORT_DOWNLOAD_EMAIL = "BLUE_AWARD_REPORT_DOWNLOAD_EMAIL",
  WEBINAR_BOOKING_CONFIRMATION = "WEBINAR_BOOKING_CONFIRMATION",
  WEBINAR_ORGANIZER_NOTIFICATION = "WEBINAR_ORGANIZER_NOTIFICATION",
  WEBINAR_REMINDER = "WEBINAR_REMINDER",
  WEBINAR_FEEDBACK_FORM = "WEBINAR_FEEDBACK_FORM",
  WEBINAR_INVITATION = "WEBINAR_INVITATION",
}

export enum EmailStatus {
  Pending = 'pending',
  Queued = 'queued',
  Sent = 'sent',
  Delivered = 'delivered',
  Error = 'error',
}
