-- ============================================================
-- Add calendar invite (.ics) mention to organizer notification
-- email template body. The attachment is now generated and sent
-- by the email server when it processes the queue.
-- Date: 2026-04-28
-- ============================================================

UPDATE [email].[NczEmailTemplates]
SET [body] = N'<!doctype html><html><head><meta charset="UTF-8"><style>body{margin:0;padding:0;background-color:#f4f4f4;font-family:Arial,sans-serif}.wrapper{max-width:600px;margin:30px auto;background:#ffffff;border-radius:6px;overflow:hidden}.header{background-color:#e3f2fd;padding:20px 40px;display:flex;align-items:center;gap:16px;border-bottom:3px solid #1565c0}.header img{height:40px;display:block;flex-shrink:0}.header h1{color:#1565c0;font-size:20px;margin:0;font-weight:600}.body{padding:36px 40px;color:#333;font-size:15px;line-height:1.6}.body h2{color:#1565c0;font-size:18px;margin-top:0}.detail-box{background:#e3f2fd;border-left:4px solid #1565c0;border-radius:4px;padding:16px 20px;margin:20px 0}.detail-box p{margin:6px 0;font-size:14px;color:#444}.detail-box strong{color:#0d47a1}.footer{background:#f9f9f9;padding:20px 40px;text-align:center;font-size:12px;color:#888;border-top:1px solid #eee}.footer a{color:#1565c0;text-decoration:none}</style></head><body><div class="wrapper"><div class="header"><img src="https://portal.nczgroup.com/assets/images/logos/ncz_logo_small.svg" alt="NCZ Logo"><h1>New Webinar Booking Received</h1></div><div class="body"><h2>A new attendee has registered</h2><p>A company has booked a slot for your webinar:</p><div class="detail-box"><p><strong>Webinar:</strong> {{webinarTitle}}</p><p><strong>Business Name:</strong> {{businessName}}</p><p><strong>Contact Email:</strong> {{contactEmail}}</p><p><strong>Slot:</strong> {{slotDateTime}}</p></div><p>&#128197; A calendar invitation (.ics file) is attached — open it to add this webinar slot to your calendar.</p><p>Log in to the NCZ Portal to view all bookings.</p><p>Best regards,<br><strong>NCZ System</strong></p></div><div class="footer">&copy; Neutral Carbon Zone &bull; <a href="https://neutralcarbonzone.com">neutralcarbonzone.com</a></div></div></body></html>'
WHERE [name] = 'WEBINAR_ORGANIZER_NOTIFICATION';
